import type { Customer, Asset, WorkOrder, MaintenanceRecord, MaintenanceTemplate, User } from "./types"

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: "CUST001",
    companyName: "Acme Manufacturing Ltd",
    industry: "Manufacturing",
    established: "2018",
    contactPerson: "John Smith",
    title: "Operations Manager",
    email: "john.smith@acme.co.ke",
    phone: "+254 712 345 678",
    address: "123 Industrial Avenue, Nairobi",
    location: "Nairobi Industrial Area",
    status: "Active",
    contractStatus: "Active",
    paymentStatus: "Current",
    monthlyAmount: 125000,
    totalEquipment: 8,
    contractExpiry: "2025-03-15",
    equipmentDetails: "3 Printers, 2 CNC, 3 Computers",
    technician: "Peter Kamau",
    supervisor: "Mary Wanjiku",
  },
  {
    id: "CUST002",
    companyName: "TechStart Innovation Inc",
    industry: "Technology",
    established: "2020",
    contactPerson: "Sarah Johnson",
    title: "CTO",
    email: "sarah.j@techstart.co.ke",
    phone: "+254 723 456 789",
    address: "456 Tech Hub, Westlands, Nairobi",
    location: "Westlands Tech Hub",
    status: "Active",
    contractStatus: "Renewal Due",
    paymentStatus: "Overdue",
    monthlyAmount: 75000,
    totalEquipment: 5,
    contractExpiry: "2024-02-29",
    equipmentDetails: "2 Printers, 1 CNC, 2 Servers",
    technician: "James Ochieng",
    supervisor: "Grace Njeri",
  },
  {
    id: "CUST003",
    companyName: "Global Industries Kenya",
    industry: "Manufacturing & Export",
    established: "2015",
    contactPerson: "Michael Davis",
    title: "Plant Manager",
    email: "m.davis@global-industries.ke",
    phone: "+254 734 567 890",
    address: "789 Export Processing Zone, Mombasa",
    location: "Mombasa EPZ",
    status: "Active",
    contractStatus: "Active",
    paymentStatus: "Current",
    monthlyAmount: 185000,
    totalEquipment: 12,
    contractExpiry: "2024-12-31",
    equipmentDetails: "4 Printers, 5 CNC, 3 Computers",
    technician: "David Kiprotich",
    supervisor: "Alice Mutua",
  },
  {
    id: "CUST004",
    companyName: "Nairobi Medical Center",
    industry: "Healthcare",
    established: "2010",
    contactPerson: "Dr. Anne Mwangi",
    title: "Director of Operations",
    email: "anne.mwangi@nairobimedical.co.ke",
    phone: "+254 745 678 901",
    address: "321 Medical Plaza, Upper Hill, Nairobi",
    location: "Upper Hill Medical Complex",
    status: "Active",
    contractStatus: "Active",
    paymentStatus: "Pending",
    monthlyAmount: 95000,
    totalEquipment: 6,
    contractExpiry: "2025-06-01",
    equipmentDetails: "2 Printers, 3 Computers, 1 Server",
    technician: "Samuel Kiptoo",
    supervisor: "Rose Wambui",
  },
  {
    id: "CUST005",
    companyName: "Coastal Logistics Solutions",
    industry: "Logistics & Transport",
    established: "2017",
    contactPerson: "Robert Kipchoge",
    title: "Fleet Manager",
    email: "robert.k@coastallogistics.co.ke",
    phone: "+254 756 789 012",
    address: "654 Port Road, Mombasa",
    location: "Mombasa Port",
    status: "Inactive",
    contractStatus: "Expired",
    paymentStatus: "N/A",
    monthlyAmount: 0,
    totalEquipment: 3,
    contractExpiry: "2023-12-31",
    equipmentDetails: "2 Printers, 1 Server",
    technician: "N/A",
    supervisor: "N/A",
  },
]

export const MOCK_ASSETS: Asset[] = [
  {
    id: "AST001",
    make: "Canon",
    model: "iR-ADV C3530i",
    serialNumber: "CN12345ABC",
    category: "Printer",
    description: "Color Multifunction Printer",
    customerId: "CUST001",
    customerName: "Acme Manufacturing Ltd",
    contactPerson: "John Smith",
    contactPhone: "+254 712 345 678",
    location: "Main Office - Floor 2",
    locationDetails: "Room 201",
    locationType: "fixed",
    condition: "good",
    status: "operational",
    purchaseDate: "2023-03-15",
    purchasePrice: 850000,
    currentValue: 850000,
    warrantyStart: "2023-03-15",
    warrantyEnd: "2026-03-15",
    warrantyProvider: "Canon Kenya Ltd",
    lastServiceDate: "2024-01-15",
    nextServiceDate: "2024-04-15",
    photoUrl: null,
    repairHistory: [
      {
        date: "2024-01-15",
        description: "Routine maintenance and toner replacement",
        cost: 8500,
        technician: "John Kamau",
      },
      {
        date: "2023-12-15",
        description: "Coolant system maintenance",
        cost: 15000,
        technician: "James Ochieng",
      },
      {
        date: "2023-09-10",
        description: "Tool changer calibration",
        cost: 8500,
        technician: "Peter Mutiso",
      },
    ],
    notes: "Primary office printer for daily operations. High usage environment.",
  },
  {
    id: "AST002",
    make: "Haas",
    model: "VF-2",
    serialNumber: "HS789XYZ",
    category: "CNC Machine",
    description: "Vertical Machining Center",
    customerId: "CUST002",
    customerName: "TechStart Innovation Inc",
    contactPerson: "Sarah Johnson",
    contactPhone: "+254 723 456 789",
    location: "Workshop Bay 3",
    locationDetails: "Production Floor",
    locationType: "fixed",
    condition: "damaged",
    status: "repair",
    purchaseDate: "2022-06-01",
    purchasePrice: 3750000,
    currentValue: 3200000,
    warrantyStart: "2022-06-01",
    warrantyEnd: "2025-01-01",
    warrantyProvider: "Haas Automation Inc",
    lastServiceDate: "2024-01-25",
    nextServiceDate: "2024-04-25",
    photoUrl: null,
    repairHistory: [
      {
        date: "2024-01-25",
        description: "Spindle bearing replacement - in progress",
        cost: 125000,
        technician: "Peter Mutiso",
      },
      {
        date: "2023-12-15",
        description: "Coolant system maintenance",
        cost: 15000,
        technician: "James Ochieng",
      },
      {
        date: "2023-09-10",
        description: "Tool changer calibration",
        cost: 8500,
        technician: "Peter Mutiso",
      },
    ],
    notes: "Critical production equipment. Currently down for major repair.",
  },
  {
    id: "AST003",
    make: "Dell",
    model: "Precision 5570",
    serialNumber: "DL456DEF",
    category: "Computer",
    description: "Mobile Workstation Laptop",
    customerId: "CUST003",
    customerName: "Global Industries Kenya",
    contactPerson: "Michael Davis",
    contactPhone: "+254 734 567 890",
    location: "Mobile Unit 1",
    locationDetails: "Field Service",
    locationType: "mobile",
    condition: "good",
    status: "maintenance",
    purchaseDate: "2023-08-10",
    purchasePrice: 325000,
    currentValue: 275000,
    warrantyStart: "2023-08-10",
    warrantyEnd: "2025-11-10",
    warrantyProvider: "Dell Kenya",
    lastServiceDate: "2024-02-10",
    nextServiceDate: "2024-05-10",
    photoUrl: null,
    repairHistory: [
      {
        date: "2024-02-10",
        description: "Software update and hardware diagnostics",
        cost: 5000,
        technician: "Grace Njeri",
      },
      {
        date: "2023-11-15",
        description: "Battery replacement",
        cost: 25000,
        technician: "John Kamau",
      },
    ],
    notes: "Field service laptop for mobile operations.",
  },
  {
    id: "AST004",
    make: "HP",
    model: "LaserJet Pro M404dn",
    serialNumber: "HP987GHI",
    category: "Printer",
    description: "Monochrome Laser Printer",
    customerId: "CUST001",
    customerName: "Acme Manufacturing Ltd",
    contactPerson: "John Smith",
    contactPhone: "+254 712 345 678",
    location: "Main Office - Floor 1",
    locationDetails: "Reception Area",
    locationType: "fixed",
    condition: "new",
    status: "operational",
    purchaseDate: "2024-01-10",
    purchasePrice: 125000,
    currentValue: 125000,
    warrantyStart: "2024-01-10",
    warrantyEnd: "2027-01-10",
    warrantyProvider: "HP Kenya",
    photoUrl: null,
    repairHistory: [],
    notes: "New printer for reception area.",
  },
]

export const MOCK_WORK_ORDERS: WorkOrder[] = [
  {
    id: "WO001",
    customerName: "Acme Manufacturing Ltd",
    contactPerson: "John Smith",
    contactPhone: "+254 712 345 678",
    equipmentName: "Canon iR-ADV C3530i",
    equipmentMake: "Canon",
    equipmentModel: "iR-ADV C3530i",
    serialNo: "CN12345ABC",
    location: "Main Office - Floor 2",
    type: "service",
    serviceType: "scheduled",
    priority: "medium",
    status: "open",
    technicianName: "John Kamau",
    supervisorName: "Mary Wanjiku",
    dueDate: "2024-02-15",
    createdDate: "2024-01-20",
    description: "Routine maintenance and toner replacement",
    pageCount: 15420,
    nextServiceDate: "2024-05-15",
    estimatedCost: 8500,
  },
  {
    id: "WO002",
    customerName: "TechStart Innovation Inc",
    contactPerson: "Sarah Johnson",
    contactPhone: "+254 723 456 789",
    equipmentName: "Haas VF-2",
    equipmentMake: "Haas",
    equipmentModel: "VF-2",
    serialNo: "HS789XYZ",
    location: "Workshop Bay 3",
    type: "repair",
    serviceType: "unscheduled",
    priority: "critical",
    status: "in-progress",
    technicianName: "Peter Mutiso",
    supervisorName: "David Kiprotich",
    dueDate: "2024-01-30",
    createdDate: "2024-01-25",
    description: "Emergency repair - Spindle bearing replacement",
    faultDescription:
      "Machine making excessive noise and vibration during operation. Customer reports grinding sound from spindle area.",
    workCarriedOut:
      "Inspected spindle assembly. Found worn bearings. Ordered replacement parts. Currently disassembling spindle unit.",
    consumableParts: [
      { name: "Spindle Bearing Kit", quantity: 1, cost: 45000 },
      { name: "Industrial Lubricant", quantity: 2, cost: 2500 },
    ],
    estimatedCost: 75000,
    actualCost: 47500,
  },
  {
    id: "WO003",
    customerName: "Global Industries Kenya",
    contactPerson: "Michael Davis",
    contactPhone: "+254 734 567 890",
    equipmentName: "Dell Precision 5570",
    equipmentMake: "Dell",
    equipmentModel: "Precision 5570",
    serialNo: "DL456DEF",
    location: "Mobile Unit 1",
    type: "service",
    serviceType: "scheduled",
    priority: "low",
    status: "assigned",
    technicianName: "Grace Njeri",
    supervisorName: "Mary Wanjiku",
    dueDate: "2024-02-20",
    createdDate: "2024-02-01",
    description: "Regular system maintenance and cleaning",
    pageCount: 0,
    nextServiceDate: "2024-05-20",
    estimatedCost: 3000,
  },
  {
    id: "WO004",
    customerName: "Nairobi Medical Center",
    contactPerson: "Dr. Anne Mwangi",
    contactPhone: "+254 745 678 901",
    equipmentName: "HP LaserJet Pro 4301",
    equipmentMake: "HP",
    equipmentModel: "LaserJet Pro 4301",
    serialNo: "HP890QWE",
    location: "Reception Area",
    type: "repair",
    serviceType: "unscheduled",
    priority: "medium",
    status: "completed",
    technicianName: "James Ochieng",
    supervisorName: "David Kiprotich",
    dueDate: "2024-02-01",
    createdDate: "2024-01-28",
    description: "Paper jam and print quality issues",
    faultDescription: "Frequent paper jams and poor print quality reported by customer",
    workCarriedOut: "Cleaned paper path, replaced pickup rollers, calibrated print heads",
    consumableParts: [
      { name: "Pickup Roller Kit", quantity: 1, cost: 1500 },
      { name: "Cleaning Kit", quantity: 1, cost: 800 },
    ],
    estimatedCost: 4000,
    actualCost: 2300,
    completedDate: "2024-02-01",
  },
  {
    id: "WO005",
    customerName: "Coastal Logistics Solutions",
    contactPerson: "Robert Kipchoge",
    contactPhone: "+254 756 789 012",
    equipmentName: "Brother MFC-L8900CDW",
    equipmentMake: "Brother",
    equipmentModel: "MFC-L8900CDW",
    serialNo: "BR123RTY",
    location: "IT Department",
    type: "service",
    serviceType: "scheduled",
    priority: "high",
    status: "cancelled",
    technicianName: null,
    supervisorName: null,
    dueDate: "2024-02-10",
    createdDate: "2024-02-05",
    description: "Preventive maintenance cancelled due to customer request",
    pageCount: 25000,
    nextServiceDate: null,
    estimatedCost: 5000,
    cancelReason: "Customer requested equipment replacement",
  },
]

export const MOCK_MAINTENANCE: MaintenanceRecord[] = [
  {
    id: "MT001",
    equipmentId: "AST001",
    equipmentName: "Canon iR-ADV C3530i",
    serialNo: "CN12345ABC",
    customerId: "CUST001",
    customerName: "Acme Manufacturing Ltd",
    type: "service",
    serviceType: "scheduled",
    description: "Toner Replacement & Cleaning",
    scheduledDate: "2024-01-28",
    status: "overdue",
    priority: "high",
    technicianId: "USR003",
    technicianName: "John Smith",
    pageCount: 15420,
    estimatedDuration: 2.5,
    createdDate: "2024-01-15",
    completedDate: null,
    actualDuration: null,
    workCarriedOut: null,
    consumableParts: [],
    notes: "Standard monthly maintenance",
  },
  {
    id: "MT002",
    equipmentId: "AST002",
    equipmentName: "Haas VF-2",
    serialNo: "HS789XYZ",
    customerId: "CUST002",
    customerName: "TechStart Innovation Inc",
    type: "repair",
    serviceType: "unscheduled",
    description: "Spindle Bearing Replacement",
    faultDescription: "Excessive vibration and noise from spindle area during operation",
    scheduledDate: "2024-02-05",
    status: "in-progress",
    priority: "medium",
    technicianId: "USR004",
    technicianName: "Mike Johnson",
    workCarriedOut: "Inspected spindle bearings, found wear. Replacement in progress.",
    consumableParts: ["Spindle Bearing Kit", "Industrial Lubricant"],
    estimatedDuration: 6.0,
    actualDuration: 3.5,
    createdDate: "2024-01-25",
    completedDate: null,
  },
  {
    id: "MT003",
    equipmentId: "AST003",
    equipmentName: "Dell Precision 5570",
    serialNo: "DL456DEF",
    customerId: "CUST003",
    customerName: "Global Industries Kenya",
    type: "service",
    serviceType: "scheduled",
    description: "Software Updates & System Cleanup",
    scheduledDate: "2024-02-10",
    status: "scheduled",
    priority: "low",
    technicianId: "USR005",
    technicianName: "Sarah Wilson",
    estimatedDuration: 1.5,
    createdDate: "2024-01-28",
    completedDate: null,
    consumableParts: [],
  },
  {
    id: "MT004",
    equipmentId: "AST001",
    equipmentName: "Canon iR-ADV C3530i",
    serialNo: "CN12345ABC",
    customerId: "CUST001",
    customerName: "Acme Manufacturing Ltd",
    type: "preventive",
    serviceType: "scheduled",
    description: "Preventive Maintenance",
    scheduledDate: "2024-03-15",
    status: "scheduled",
    priority: "medium",
    technicianId: "USR003",
    technicianName: "John Smith",
    estimatedDuration: 3.0,
    createdDate: "2024-02-01",
    completedDate: null,
    consumableParts: [],
  },
  {
    id: "MT005",
    equipmentId: "AST002",
    equipmentName: "Haas VF-2",
    serialNo: "HS789XYZ",
    customerId: "CUST002",
    customerName: "TechStart Innovation Inc",
    type: "emergency",
    serviceType: "unscheduled",
    description: "Emergency Repair - Motor Failure",
    faultDescription: "Main spindle motor seized during operation, complete failure",
    scheduledDate: "2024-01-30",
    status: "completed",
    priority: "critical",
    technicianId: "USR004",
    technicianName: "Mike Johnson",
    estimatedDuration: 8.0,
    actualDuration: 10.5,
    createdDate: "2024-01-30",
    completedDate: "2024-02-01",
    workCarriedOut: "Replaced main spindle motor, tested all systems, calibrated machine",
    consumableParts: ["Spindle Motor Assembly", "Coupling Kit", "Hydraulic Fluid"],
  },
]

export const MOCK_MAINTENANCE_TEMPLATES: MaintenanceTemplate[] = [
  {
    id: "TPL001",
    name: "Printer Service Template",
    description: "Monthly maintenance for Canon and HP printers",
    type: "service",
    estimatedDuration: 0.75,
    checklist: [
      "Check toner levels",
      "Clean print heads",
      "Check paper feed mechanism",
      "Update firmware if available",
      "Test print quality",
      "Clean exterior surfaces",
      "Check for error logs",
      "Document page count",
    ],
    notes: "Standard monthly printer maintenance procedure",
  },
  {
    id: "TPL002",
    name: "CNC Machine Preventive",
    description: "Quarterly preventive maintenance for CNC machines",
    type: "preventive",
    estimatedDuration: 3.0,
    checklist: [
      "Inspect spindle bearings",
      "Check coolant system",
      "Lubricate moving parts",
      "Calibrate tool changer",
      "Test emergency stops",
      "Check hydraulic pressure",
      "Inspect electrical connections",
      "Update machine firmware",
      "Run test programs",
    ],
    notes: "Comprehensive quarterly maintenance for CNC equipment",
  },
  {
    id: "TPL003",
    name: "Computer Workstation Service",
    description: "Standard maintenance for desktop and laptop computers",
    type: "service",
    estimatedDuration: 1.0,
    checklist: [
      "Run system diagnostics",
      "Update operating system",
      "Update installed software",
      "Run antivirus scan",
      "Clean temporary files",
      "Check disk health",
      "Test battery (laptops)",
      "Clean exterior and vents",
    ],
    notes: "Regular computer maintenance procedure",
  },
]

export const MOCK_USERS: User[] = [
  {
    id: "USR001",
    email: "admin@emmis.co.ke",
    name: "Admin User",
    role: "admin",
    phone: "+254 700 000 001",
    department: "Administration",
    status: "active",
    lastLogin: "2024-02-15T10:30:00",
    createdDate: "2023-01-15",
  },
  {
    id: "USR002",
    email: "supervisor@emmis.co.ke",
    name: "Mary Wanjiku",
    role: "supervisor",
    phone: "+254 700 000 002",
    department: "Operations",
    status: "active",
    lastLogin: "2024-02-15T09:15:00",
    createdDate: "2023-02-20",
  },
  {
    id: "USR003",
    email: "john.kamau@emmis.co.ke",
    name: "John Kamau",
    role: "technician",
    phone: "+254 712 345 001",
    department: "Field Service",
    status: "active",
    lastLogin: "2024-02-15T08:45:00",
    createdDate: "2023-03-10",
  },
  {
    id: "USR004",
    email: "peter.mutiso@emmis.co.ke",
    name: "Peter Mutiso",
    role: "technician",
    phone: "+254 712 345 002",
    department: "Field Service",
    status: "active",
    lastLogin: "2024-02-14T16:20:00",
    createdDate: "2023-04-05",
  },
  {
    id: "USR005",
    email: "grace.njeri@emmis.co.ke",
    name: "Grace Njeri",
    role: "technician",
    phone: "+254 712 345 003",
    department: "IT Support",
    status: "active",
    lastLogin: "2024-02-15T07:30:00",
    createdDate: "2023-05-12",
  },
  {
    id: "USR006",
    email: "james.ochieng@emmis.co.ke",
    name: "James Ochieng",
    role: "technician",
    phone: "+254 712 345 004",
    department: "Field Service",
    status: "inactive",
    lastLogin: "2024-01-20T14:00:00",
    createdDate: "2023-06-18",
  },
  {
    id: "USR007",
    email: "david.kiprotich@emmis.co.ke",
    name: "David Kiprotich",
    role: "supervisor",
    phone: "+254 700 000 003",
    department: "Operations",
    status: "active",
    lastLogin: "2024-02-15T09:00:00",
    createdDate: "2023-07-22",
  },
  {
    id: "USR008",
    email: "alice.mutua@emmis.co.ke",
    name: "Alice Mutua",
    role: "supervisor",
    phone: "+254 700 000 004",
    department: "Quality Assurance",
    status: "suspended",
    lastLogin: "2024-01-15T11:30:00",
    createdDate: "2023-08-30",
  },
]
